export enum SpentType {
    SHOPPING = 'Shopping',
    FOOD = 'Food',
    CLOTHES = 'Clothes',
    TRANSPORTATION = 'Transportation',
    TRAVEL = 'Travel',
    BILLS = 'Bills',
    GIFT = 'Gift',
    EDUCATION = 'Education',
    SNACKS = 'Snacks',
    TELEPHONE = 'Telephone',
    ELECTRONICS = 'Electronics',
    ENTERTAINMENT = 'Entertainment',
    BEAUTY = 'Beauty',
}